# @package _global_
task_name: hover
# name: arcdrone
# file_path: task/arcdrone.py


env:
  
  # ==== General setup ====
  numEnvs: 2
  mj_timestep: 0.004  # 250Hz simulation timestep
  n_frames: 5         # 250/5 = 50Hz controller
  backend: "mjx"
  xml_path_rel: "assets/skydio_x2/scene.xml"  # "assets/arcdrone/scene.xml"
  eval_mode: False
  
  
  # ==== Task specific ====

  buffer_size: 5

  # Episode control
  max_episode_steps: 200   
  success_threshold: 0.02
  success_steps_required: 10
  
  # Reward function
  distance_weight: 1 
  distance_scale: 0.3  # exponential          
  overshoot_penalty: 5
  oscillation_penalty: 2
  action_chattering_weight: 0.001
  action_penalty_weight: 0.0001
  time_penalty: 0.01 
  success_bonus: 50.0
  ground_penalty_weight: 10.0  
  ground_threshold_event: 0.15  
  ground_threshold_penalty: 0.5 

  # Sensor noise
  linacc_noise: 0.02  # m/s²
  quat_noise: 0.001   # dimensionless
  angvel_noise: 0.01  # rad/s
  linvel_noise: 0.01  # m/s
  

  


  



train:


  # PPO Hyperparameters
  num_timesteps: 100 # 20_000_000
  num_evals: 5
  reward_scaling: 0.1
  episode_length: ${env.max_episode_steps}
  normalize_observations: true
  action_repeat: 1
  unroll_length: 10
  num_minibatches: 24
  num_updates_per_batch: 8
  log_training_metrics: false
  discounting: 0.97
  learning_rate: 3e-4
  entropy_cost: 1e-3
  num_envs: ${env.numEnvs}
  batch_size: 512
  seed: 0

  
  # Network Architecture
  policy_hidden_layers: [512, 512, 256, 128]
  value_hidden_layers: [512, 512, 256, 128]
  policy_obs_key: "state"
  value_obs_key: "privileged_state"

  
  # WandB Configuration
  use_wandb: true
  wandb_project: "brax-training"
  wandb_run_name: "arcdrone_vel_ppo_run"

  
  # Train from checkpoint (for continuing training)
  restore_params_path: null      
  restore_value_fn: true    

  



