# cfg/config.yaml

defaults:
  - task: hover
  - train: ${task}_ppo      # I dont know why this works, but does.
  - override hydra/job_logging: default  
  - override hydra/hydra_logging: default  
  - _self_

# Global configuration flags
debug_cpu: false  # Set to true to force CPU mode for debugging

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}