train:

  # PPO Hyperparameters
  num_timesteps: 100 # 20_000_000
  num_evals: 5
  reward_scaling: 0.1
  episode_length: 200
  normalize_observations: true
  action_repeat: 1
  unroll_length: 10
  num_minibatches: 24
  num_updates_per_batch: 8
  log_training_metrics: false
  discounting: 0.97
  learning_rate: 3e-4
  entropy_cost: 1e-3
  # Default number of parallel environments. Task configs can override.
  num_envs: 2
  batch_size: 512
  seed: 0


  # Train from checkpoint (for continuing training)
  restore_params_path: null      
  restore_value_fn: true 
  frompreviouscheckpoint: 0   # 0,1,2,3. This flag overrides the two previous ones. 0 sets false. 1 sets true and uses the last checkpoint. 2 sets true and uses the one before last checkpoint. 3 sets true and uses the one before that.
  
