task_name: vision_landing_ppo

defaults:
  - override hydra/job_logging: default  
  - override hydra/hydra_logging: default  
  - _self_


hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}


env:
  
  # ==== MJXEnvs / mujoco_playground flags ====
  xml_path_rel: "assets/skydio_x2/scene.xml"  # "assets/arcdrone/scene.xml"
  impl: "warp"
  sim_dt: 0.004
  ctrl_dt: 0.02
  action_repeat: 1
  naconmax: 0
  njmax: 2
  vision: true
  vision_config: # must contain only warp api parameters
    nworld: ${train.num_envs}
    cam_res: [64, 64]
    use_textures: false
    use_shadows: false
    enabled_geom_groups: [0, 1, 2]
    cam_active: [true, false, false]
    render_rgb: [true]
    render_depth: [false]
  
  # ==== Task specific ====

  buffer_size: 5

  # Episode control
  max_episode_steps: ${train.episode_length}
  success_threshold: 0.02
  success_steps_required: 10
  
  # Reward function
  distance_weight: 1 
  distance_scale: 0.3  # exponential          
  overshoot_penalty: 5
  oscillation_penalty: 2
  action_chattering_weight: 0.001
  action_penalty_weight: 0.0001
  time_penalty: 0.01 
  success_bonus: 500.0
  ground_penalty_weight: 10.0  
  ground_threshold_event: 0.15  
  ground_threshold_penalty: 0.5 


train:

  # PPO Hyperparameters
  num_timesteps: 100 # 20_000_000
  num_evals: 8
  num_eval_envs: 2
  reward_scaling: 0.1
  episode_length: 200
  normalize_observations: true
  action_repeat: 1
  unroll_length: 10
  num_minibatches: 24
  num_updates_per_batch: 8
  log_training_metrics: false
  discounting: 0.97
  learning_rate: 3e-4
  entropy_cost: 1e-3
  # Default number of parallel environments. Task configs can override.
  num_envs: 2
  batch_size: 512
  seed: 0

  # Network Architecture
  policy_dec_hidden_layers: [256, 256]
  policy_propio_proj_hidden_layers: [64]
  action_hidden_layers: [64]
  value_hidden_layers: [256, 256, 256]
  cnn_num_filters: [32, 64, 64]
  cnn_kernel_sizes: [[8, 8], [4, 4], [3, 3]]
  cnn_strides: [[4, 4], [2, 2], [1, 1]]
  policy_pixels_key: "pixels/view_0"
  policy_propio_key: "propio"
  value_obs_key: "value_obs"

  # Train from checkpoint (for continuing training)
  restore_params_path: null      
  restore_value_fn: true 
  frompreviouscheckpoint: 0   # 0,1,2,3. This flag overrides the two previous ones. 0 sets false. 1 sets true and uses the last checkpoint. 2 sets true and uses the one before last checkpoint. 3 sets true and uses the one before that.

  # WandB Configuration
  wandb_project: "brax-training"
  wandb_run_name: "arcdrone_vision_landing_ppo_run"
  use_wandb: false


  


  






