_wandb:
    value:
        cli_version: 0.24.2
        e:
            q1hvftfb6v457q3b730mvjr2gb7j2nk6:
                args:
                    - train.num_envs=2056
                    - train.unroll_length=32
                    - train.batch_size=1028
                    - train.num_minibatches=16
                    - train.num_updates_per_batch=16
                    - train.num_timesteps=10000000
                    - train.use_wandb=true
                    - train.num_evals=30
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "157681115136"
                        used: "74640543744"
                email: jraimundo.mares.12@gmail.com
                executable: /home/jrmch12f/miniconda3/envs/arcdrone/bin/python3.11
                git:
                    commit: 5f282c9b2df871a10a20a29a9b97732a4aa823ef
                    remote: git@github.com:jrmch12/borrador_braxenvs.git
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-08497d9e-c6e9-769a-e3c6-db02e12d0e13
                host: jrmch12f
                memory:
                    total: "16643227648"
                os: Linux-6.8.0-100-generic-x86_64-with-glibc2.35
                program: /home/jrmch12f/miniconda3/envs/arcdrone/bin/arcdrone-train
                python: CPython 3.11.0
                root: /home/jrmch12f/Documents/code/borrador_braxenvs
                startedAt: "2026-02-23T17:41:02.888910Z"
                writerId: q1hvftfb6v457q3b730mvjr2gb7j2nk6
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 12
                - 45
                - 50
            "2":
                - 12
                - 45
                - 50
            "3":
                - 13
                - 16
            "4": 3.11.0
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
debug_cpu:
    value: false
env:
    value:
        action_chattering_weight: 0.001
        action_penalty_weight: 0.0001
        angvel_noise: 0.01
        backend: mjx
        buffer_size: 5
        distance_scale: 5
        distance_weight: 1
        eval_mode: false
        ground_penalty_weight: 100
        ground_threshold: 0.1
        linacc_noise: 0.02
        linvel_noise: 0.01
        max_episode_steps: 200
        mj_timestep: 0.004
        n_frames: 5
        numEnvs: 2
        oscillation_penalty: 2
        overshoot_penalty: 5
        quat_noise: 0.001
        success_bonus: 50
        success_steps_required: 10
        success_threshold: 0.02
        time_penalty: 0.01
        xml_path_rel: assets/skydio_x2/scene.xml
file_path:
    value: task/arcdrone.py
name:
    value: arcdrone
train:
    value:
        action_repeat: 1
        batch_size: 1028
        discounting: 0.97
        entropy_cost: 0.001
        episode_length: 200
        learning_rate: 0.0003
        log_training_metrics: false
        normalize_observations: true
        num_envs: 2056
        num_evals: 30
        num_minibatches: 16
        num_timesteps: 10000000
        num_updates_per_batch: 16
        policy_hidden_layers:
            - 512
            - 512
            - 256
            - 128
        policy_obs_key: state
        restore_params_path: null
        restore_value_fn: true
        reward_scaling: 0.1
        seed: 0
        unroll_length: 32
        use_wandb: true
        value_hidden_layers:
            - 512
            - 512
            - 256
            - 128
        value_obs_key: privileged_state
        wandb_project: brax-training
        wandb_run_name: arcdrone_vel_ppo_run
